### ISSUE TITLE
Lossless video format (using jcodec) not supported by dl4j

### ISSUE THREAD

**Issue by someonedeep** [deeplearning4j/DataVec#104]
I have generated labelled videos using jcodec 1.5 and 1.9, both using the standard SequenceEncoder.

SequenceEncoder encoder = new SequenceEncoder(new File(<Name Video>));
BufferedImage bi = ImageIO.read(<Some Image File>);
encoder.encodeNativeFrame(AWTUtil.fromBufferedImage(bi));
encoder.finish.

This results in lossy videos, see screenshot below.

I also generate videos as was written here: http://stackoverflow.com/questions/11345343/png-image-files-to-video-lossless
 
This results in lossless videos, which are also much smaller (again, see screenshot). However, dl4j does not load these images. In jcodec 1.5 I receive codec not supported, and using jcodec 1.9 I receive the following error :

Exception in thread "main" java.lang.RuntimeException: Exception thrown in base iterator
	at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator.next(AsyncDataSetIterator.java:231)
	at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator.next(AsyncDataSetIterator.java:36)
	at TrackingPredictions.VideoClassification.main(VideoClassification.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.NullPointerException
	at org.jcodec.containers.mp4.demuxer.FramesMP4DemuxerTrack.getMeta(FramesMP4DemuxerTrack.java:203)
	at org.jcodec.api.FrameGrab.detectKeyFrame(FrameGrab.java:211)
	at org.jcodec.api.FrameGrab.decodeLeadingFrames(FrameGrab.java:188)
	at org.jcodec.api.FrameGrab.<init>(FrameGrab.java:85)
	at org.datavec.codec.reader.CodecRecordReader.loadData(CodecRecordReader.java:107)
	at org.datavec.codec.reader.CodecRecordReader.sequenceRecord(CodecRecordReader.java:85)
	at org.deeplearning4j.datasets.datavec.SequenceRecordReaderDataSetIterator.nextMultipleSequenceReaders(SequenceRecordReaderDataSetIterator.java:200)
	at org.deeplearning4j.datasets.datavec.SequenceRecordReaderDataSetIterator.next(SequenceRecordReaderDataSetIterator.java:133)
	at org.deeplearning4j.datasets.datavec.SequenceRecordReaderDataSetIterator.next(SequenceRecordReaderDataSetIterator.java:115)
	at org.deeplearning4j.datasets.datavec.SequenceRecordReaderDataSetIterator.next(SequenceRecordReaderDataSetIterator.java:29)
	at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator$IteratorRunnable.run(AsyncDataSetIterator.java:300)
	at java.lang.Thread.run(Thread.java:745)

I assume that lossless videos yield in better learning performances, and that smaller videos most likely in speed performances..

**Comment by someonedeep** [comment]
Screenshot from lossy and lossless video:

![videos](https://cloud.githubusercontent.com/assets/22542942/20828043/db217798-b875-11e6-920e-d1c2ba4bdd4c.png)

**Comment by someonedeep** [comment]
Screenshot from both videos, lossy and lossless.
![videos](https://cloud.githubusercontent.com/assets/22542942/20828102/2245e262-b876-11e6-822f-1b2b8c4f2276.png)

**Comment by saudet** [comment]
The plan is to switch to FFmpeg, which everyone -- [including Chrome](https://www.chromium.org/audio-video) -- is using these days, but it's LPGL, so we need advice from our legal team, @agibsonccc ? :)

**Comment by agibsonccc** [comment]
We can't have it as a first class module. We will have to maintain 2
versions of the software.

**Comment by saudet** [comment]
@someonedeep I've added `NativeCodecRecordReader` that uses FFmpeg and can decode pretty much any video file, but we need to add a dependency on JavaCV manually, for licensing reasons. For example, in the case of Maven:
```xml
  <dependency>
    <groupId>org.bytedeco</groupId>
    <artifactId>javacv-platform</artifactId>
    <version>1.3.1</version>
  </dependency>
```

**Comment by agibsonccc** [comment]
@saudet could you add a description on this somewhere on the deeplearning4j.org website on the datavec page? Maybe create a section called video?

**Comment by saudet** [comment]
There's already something about that on the site: https://deeplearning4j.org/simple-image-load-transform#javacv--opencv-and-ffmpeg-filters  How do you think we should modify @tomthetrainer ?

**Comment by agibsonccc** [comment]
Ahh even a link from the datavec page here woul dbe great I had forgotten about this page :D.

**Comment by someonedeep** [comment]
Hi, i tested the NativeCodecRecordReader (copy pasted BaseCodecRecordReader, NativeCodecRecordReader, CodecRecordReader to my own project, which uses also the 0.7.2 version of dl4j) and it now trains a model based on lossless videos. Thank you and keep up the excellent work.

If this is published in the new maven version, I hope to be informed.

**Comment by saudet** [comment]
Great! Thanks for the feedback. It will be in the next release, either 0.7.3 or more likely 0.8.0. To be informed, you can subscribe to the mailing list at the bottom on this page: https://deeplearning4j.org/

**Comment by tomthetrainer** [comment]
I will add a discussion about opencv and ffmpeg filters to the re-write of the data ingestion that includes scaler, transform, normalizer etc.
