### ISSUE TITLE
Error in datavec-data-image test

### ISSUE THREAD

**Issue by rkrish999** [deeplearning4j/DataVec#114]
Downloaded datavec and trying to build it on windows 10.

Test fails with:
Tests run: 9, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.988 sec <<< FAILURE! - in org.datavec.image.transform.TestImageTransform
testFilterImageTransform(org.datavec.image.transform.TestImageTransform)  Time elapsed: 0.072 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil
        at org.bytedeco.javacv.FFmpegFrameFilter.startUnsafe(FFmpegFrameFilter.java:158)
        at org.bytedeco.javacv.FFmpegFrameFilter.start(FFmpegFrameFilter.java:154)
        at org.datavec.image.transform.FilterImageTransform.<init>(FilterImageTransform.java:61)
        at org.datavec.image.transform.TestImageTransform.testFilterImageTransform(TestImageTransform.java:135)

Error putting member offsets for class org/bytedeco/javacpp/avutil$Pool_free_Pointer.

**Comment by saudet** [comment]
Please try again with a more recent version of Maven.
