### ISSUE TITLE
failure in CSVSparkTransformServerTest test

### ISSUE THREAD

**Issue by kepricon** [deeplearning4j/DataVec#322]
#### Issue Description

It looks [CSVSparkTransformServerTest](https://github.com/deeplearning4j/DataVec/blob/master/datavec-spark-inference-parent/datavec-spark-inference-server/src/test/java/org/datavec/spark/transform/CSVSparkTransformServerTest.java) has failed.

here's the part of messages.
```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: ; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3609)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3549)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2580)
	at org.datavec.spark.transform.CSVSparkTransformServerTest$1.readValue(CSVSparkTransformServerTest.java:43)
	... 28 more
```

[this](https://gist.github.com/kepricon/9c722e7a2679e8eb867275fc4b1668da) is full messages.

#### Version Information

current master(9c2b024dd9e3812e9219ce947bc4cb635865ff93)

/cc @agibsonccc

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/DataVec/pull/323
