### ISSUE TITLE
NotSerializableException for DispatchOp when using reduce in TransformProcess

### ISSUE THREAD

**Issue by turambar** [deeplearning4j/DataVec#326]
#### Issue Description

Using a reduce operation inside of a TransformProcess throws a `java.io.NotSerializableException` for `org.datavec.api.transform.ops.DispatchOp`.

To reproduce, run the DataVec [PivotExample.java](https://github.com/deeplearning4j/dl4j-examples/blob/master/datavec-examples/src/main/java/org/datavec/transform/basic/PivotExample.java) using the latest 0.8.1-SNAPSHOT from the snapshots repository. You'll get this error:

```
Exception in thread "main" java.io.NotSerializableException: org.datavec.api.transform.ops.DispatchOp
Serialization stack:
	- object not serializable (class: org.datavec.api.transform.ops.DispatchOp, value: org.datavec.api.transform.ops.DispatchOp@68dd39d2)
	at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:40)
	at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:47)
	at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:101)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$aggregateByKey$1.apply(PairRDDFunctions.scala:168)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$aggregateByKey$1.apply(PairRDDFunctions.scala:166)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
	at org.apache.spark.rdd.PairRDDFunctions.aggregateByKey(PairRDDFunctions.scala:166)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$aggregateByKey$3.apply(PairRDDFunctions.scala:206)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$aggregateByKey$3.apply(PairRDDFunctions.scala:206)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
	at org.apache.spark.rdd.PairRDDFunctions.aggregateByKey(PairRDDFunctions.scala:205)
	at org.apache.spark.api.java.JavaPairRDD.aggregateByKey(JavaPairRDD.scala:353)
	at org.datavec.spark.transform.SparkTransformExecutor.execute(SparkTransformExecutor.java:258)
	at org.datavec.spark.transform.SparkTransformExecutor.execute(SparkTransformExecutor.java:97)
	at org.datavec.transform.basic.PivotExample.main(PivotExample.java:92)
```

#### Version Information

* Latest dl4j-examples
* Latest 0.8.1-SNAPSHOT snapshot from the sonatype snapshots repository

**Comment by AlexDBlack** [comment]
```DispatchOp<T, U> implements IAggregableReduceOp<List<T>, List<U>>``` and IAggregableReduceOp was made serializable here: https://github.com/deeplearning4j/DataVec/pull/328
