### ISSUE TITLE
Datavec-api & Datavec-dataframe have conflicting dependencies for fastutils

### ISSUE THREAD

**Issue by MikeDepies** [deeplearning4j/DataVec#342]
Datavec-api has the following dependency:
`
[INFO] |  +- org.nd4j:nd4j-common:jar:0.8.0:compile
[INFO] |  \- com.clearspring.analytics:stream:jar:2.7.0:compile
[INFO] |     \- it.unimi.dsi:fastutil:jar:6.5.7:compile
`

This conflicts with dataframe's declaration of the it.unimi.dsi:fastutil:jar7.0.6.
Updating the dependency for clearspring.analytics brings it to 7.0.1 which solves an issue with a function in dataframe's codebase
`
Exception in thread "main" java.lang.NoSuchMethodError: it.unimi.dsi.fastutil.ints.IntArrays.parallelQuickSort([ILit/unimi/dsi/fastutil/ints/IntComparator;)V
	at org.datavec.dataframe.api.Table.sortOn(Table.java:551)
	at org.datavec.dataframe.api.Table.sortOn(Table.java:497)
	at org.datavec.dataframe.api.Table.sortOn(Table.java:457)
	at org.datavec.dataframe.table.ViewGroup.<init>(ViewGroup.java:42)
	at org.datavec.dataframe.table.ViewGroup.create(ViewGroup.java:48)
	at org.datavec.dataframe.reducing.functions.SummaryFunction.by(SummaryFunction.java:30)
	...
`
Simple solution for now is to define dependency management rules in the pom
`<dependencyManagement>
  <dependencies>
      <dependency>
         <groupId>it.unimi.dsi</groupId>
         <artifactId>fastutil</artifactId>
         <version>7.0.6</version>
      </dependency>
  </dependencies>
</dependencyManagement>`

**Comment by agibsonccc** [comment]
Due to de forking, we are closing this.
