### ISSUE TITLE
Have graphical tests check the value of `awt.java.headless`

### ISSUE THREAD

**Issue by huitseeker** [deeplearning4j/DataVec#371]
#### Issue Description
Our test / CI machine, for instance, runs with : 

```
huitseeker@spotty-canary:/mnt/datavec$ echo $MAVEN_OPTS
-Dawt.java.headless=true
```

This is meant to tell graphical tests (e.g. `TestImageTransform`)  to not run because there is no screen to attach this test to. Yet testing outputs the following:

   ```

testShowImageTransform(org.datavec.image.transform.TestImageTransform)  Time elapsed: 0.002 sec  <<< ERROR!
java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at javax.swing.JFrame.<init>(JFrame.java:233)
	at org.bytedeco.javacv.CanvasFrame.<init>(CanvasFrame.java:124)
	at org.datavec.image.transform.ShowImageTransform.<init>(ShowImageTransform.java:66)
	at org.datavec.image.transform.TestImageTransform.testShowImageTransform(TestImageTransform.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
```

Full log : https://gist.github.com/f47b8f2e28490ef859a05dddb622e4eb

**Comment by huitseeker** [comment]
My bad, it's supposed to be `-Djava.awt.headless=true` not `-Dawt.java.headless=true`
See http://www.oracle.com/technetwork/articles/javase/headless-136834.html

**Comment by huitseeker** [comment]
There really was an issue, but it's being closed by https://github.com/deeplearning4j/DataVec/pull/382
