### ISSUE TITLE
Error using StringToWritablesFunction with pipe-delimited RecordReader

### ISSUE THREAD

**Issue by mdebeer** [deeplearning4j/DataVec#419]
#### Issue Description

Here is a cut of my data file:
```
17|0|0|2016-03-20 00:00:00.0000000|1|13|1|0||
17|0|0|2016-03-27 00:00:00.0000000|1|95|1|0||
17|0|0|2016-04-03 00:00:00.0000000|1|15|1|0||
17|0|0|2016-04-10 00:00:00.0000000|1|25|1|0||
17|0|0|2016-04-17 00:00:00.0000000|1|4|0|0||
18|0|0|2016-03-20 00:00:00.0000000|1|60|1|0||
18|0|0|2016-03-27 00:00:00.0000000|1|24|1|0||
18|0|0|2016-04-03 00:00:00.0000000|1|16|1|0||
18|0|0|2016-04-10 00:00:00.0000000|1|85|1|0||
18|0|0|2016-04-17 00:00:00.0000000|1|38|0|0||
```

I have created an input Schema and a TransformProcess to read and filter the data, as follows:
```
Schema inputDataSchema = new Schema.Builder()
            .addColumnsInteger("DeviceID","DayNo","StartHour")
            .addColumnString("DateTime")
            .addColumnsInteger("EndHour","Consumption","HourComplete","DeliveryInProgress","Fallback","FallbackDateTime")
            .build();

TransformProcess tp = new TransformProcess.Builder(inputDataSchema)
            .removeColumns("EndHour","Fallback","FallbackDateTime")
            .stringToTimeTransform("DateTime","YYYY-MM-dd HH:mm:ss.SSSSSSS", DateTimeZone.getDefault())
            .filter(new ConditionFilter(
                new IntegerColumnCondition( "DeviceID", ConditionOp.NotEqual, 17)))
            .build();
```
So the transform removes some columns, converts DateTime from string, and filters by ID.

This is applied using the method from BasicDataVecExample:
```
SparkConf conf = new SparkConf();
conf.setMaster("local[*]");
conf.setAppName("DataReadTest");
JavaSparkContext sc = new JavaSparkContext(conf);

JavaRDD<String> stringData = sc.textFile(inputPath);

RecordReader rr = new CSVRecordReader(0, '|'); 
//This initialisation is confirmed to work with pipe as per issue #414

JavaRDD<List<Writable>> parsedInputData = stringData.map(new StringToWritablesFunction(rr));

//Execute the transform
JavaRDD<List<Writable>> processedData = SparkTransformExecutor.execute(parsedInputData, tp);
//This line returns the error, implying that parsedInputData was not generated correctly

//Collect data and print
JavaRDD<String> processedAsString = processedData.map(new WritablesToStringFunction("|"));

List<String> processedCollected = processedAsString.collect();
List<String> inputDataCollected = stringData.collect();

System.out.println("\n\n---- Original Data ----");
for(String s : inputDataCollected) System.out.println(s);

System.out.println("\n\n---- Processed Data ----");
for(String s : processedCollected) System.out.println(s);
```

With pipe as delimiter it returns the following error:
```
java.lang.IllegalStateException: Input data number of columns (1) does not match the number of columns for the transform process (10)
        at org.datavec.spark.transform.SparkTransformExecutor.execute(SparkTransformExecutor.java:173)
        at org.datavec.spark.transform.SparkTransformExecutor.execute(SparkTransformExecutor.java:94)
        ...
```

If I change the file's delimiter to comma or semicolon, it succeeds:
```
---- Original Data ----
17,0,0,2016-03-20 00:00:00.0000000,1,13,1,0,,
17,0,0,2016-03-27 00:00:00.0000000,1,95,1,0,,
17,0,0,2016-04-03 00:00:00.0000000,1,15,1,0,,
17,0,0,2016-04-10 00:00:00.0000000,1,25,1,0,,
17,0,0,2016-04-17 00:00:00.0000000,1,4,0,0,,
18,0,0,2016-03-20 00:00:00.0000000,1,60,1,0,,
18,0,0,2016-03-27 00:00:00.0000000,1,24,1,0,,
18,0,0,2016-04-03 00:00:00.0000000,1,16,1,0,,
18,0,0,2016-04-10 00:00:00.0000000,1,85,1,0,,
18,0,0,2016-04-17 00:00:00.0000000,1,38,0,0,,


---- Processed Data ----
17,0,0,1458424800000,13,1,0
17,0,0,1459029600000,95,1,0
17,0,0,1459634400000,15,1,0
17,0,0,1460239200000,25,1,0
17,0,0,1460844000000,4,0,0
```

You may think we should just swap delimiters to avoid the problem, but in practice it will not be so simple -- and it's worthwhile to report nonetheless, because it should of course work with any delimiter.

P.S. Along the way I noted that the BasicDataVecExample uses (line 103)           `.stringToTimeTransform("DateTimeString","YYYY-MM-DD HH:mm:ss.SSS", DateTimeZone.UTC)`
where JodaTime reads **DD** as "day of the year", which works in the example as the example dates are in January, but it should instead use **dd** for "day of the month". This way a first-time user could use that transform example without hiccups.

#### Version Information
* Deeplearning4j: 0.9.1
* platform: Arch Linux

**Comment by MrDallOca** [comment]
I've just got a similar error and bumped into this issue.

Tried something like `new CSVRecordReader(0, ';');` but it didn't seem to make a difference.

**Comment by AlexDBlack** [comment]
Turns out: this was due to a serialization issue. Fixed here: https://github.com/deeplearning4j/DataVec/pull/474

Basically, the delimiter etc configs get reset to the defaults (comma separated).

Two workarounds:
(a) ```sc.textFile(inputPath).map(<replace all delimiters with commas>)```
(b) Make a copy of CSVRecordReader + SerializableCSVParser (from current master), in your own project

**Comment by AlexDBlack** [comment]
Update/FYI - java serialization is fixed, Kryo is still an issue. That will be fixed shortly.
https://github.com/deeplearning4j/DataVec/issues/477
