### ISSUE TITLE
Unexpected exception when changing the number of dataset.

### ISSUE THREAD

**Issue by eypros** [deeplearning4j/DataVec#434]
Unexpected exception when changing the size of the dataset.

The execution of the code from [AnimalsClassification](https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/convolution/AnimalsClassification.java) with just a minor change in the number of samples to be taken into consideration for the neural network produce an exception of Unsupported Operation.

The minor change could be:
`numExamples = 64;` instead of the initial 80.

Some about the problem NN attempts to solve:

- There  are 4 classes of images with animals 

- Each class contains roughly 20 samples (one class contains 22 and one 21 I think but all have equal or more than 20 samples).

```
Exception in thread "ADSI prefetch thread" java.lang.RuntimeException: java.lang.UnsupportedOperationException: Cannot do conversion to one hot using batched reader: 4 output classes, but array.size(1) is 3 (must be equal to 1 or numClasses = 4)
	at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator$AsyncPrefetchThread.run(AsyncDataSetIterator.java:442)
Caused by: java.lang.UnsupportedOperationException: Cannot do conversion to one hot using batched reader: 4 output classes, but array.size(1) is 3 (must be equal to 1 or numClasses = 4)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertWritablesBatched(RecordReaderMultiDataSetIterator.java:314)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertFeaturesOrLabels(RecordReaderMultiDataSetIterator.java:267)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.nextMultiDataSet(RecordReaderMultiDataSetIterator.java:240)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.next(RecordReaderMultiDataSetIterator.java:177)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:306)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:393)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:51)
	at org.deeplearning4j.datasets.iterator.MultipleEpochsIterator.next(MultipleEpochsIterator.java:118)
	at org.deeplearning4j.datasets.iterator.MultipleEpochsIterator.next(MultipleEpochsIterator.java:144)
	at org.deeplearning4j.datasets.iterator.MultipleEpochsIterator.next(MultipleEpochsIterator.java:38)
	at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator$AsyncPrefetchThread.run(AsyncDataSetIterator.java:423)
```

I don't provide the code since it's the same from the examples.
The problem is reproducible if the number of samples increases to 120 for example (new samples added to every class folder) and the parameter `numExamples` stays the same (that is `numExamples = 80;`)

#### Version Information

* Deeplearning4j 0.9.1
* win7
* no CUDA or NVIDIA

**Comment by kamir** [comment]
I was running into the same issue.

**Comment by scto1022** [comment]
Hey! I am having the same problem - did you mange to solve it ?

**Comment by AlexDBlack** [comment]
Looking at this again: the most likely cause here is that the number of labels (according to ImageRecordReader) doesn't match the number of labels provided to RecordReader(Multi)DataSetIterator.

You can either do a setLabels on the ImageRecordReader (to specify the exact labels), or fix the argument passed to RecordReader(Multi)DataSetIterator to match the number of labels inferred by ImageRecordReader.

My guess is that in at least some of these cases, some of the labels just don't have any examples for ImageRecordReader to see. So say you have labels {A, B, C} yet (by filtering or whatever) end up with 20xA, 40xB, and 0xC, ImageRecordReader will think (legitimately) that you only have 2 classes.
