### ISSUE TITLE
Field charset from RegexSequenceRecordReader cannot be serialized by Spark

### ISSUE THREAD

**Issue by nlebreton** [deeplearning4j/DataVec#464]
Hi,

The following exception is thrown in the method stringData.map(..) while calling the 3 lines below:

		JavaRDD<String> stringData = sparkContext.textFile(filePath);
		RegexSequenceRecordReader recordReader = new RegexSequenceRecordReader(REG_EXP, 0, Charset.forName("UTF-8"), LineErrorHandling.SkipInvalid);		
		JavaRDD<List<Writable>> parsedInputData = stringData.map(new StringToWritablesFunction(recordReader));

Exception thrown:

Exception in thread "main" org.apache.spark.SparkException: Task not serializable
	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:298)
	at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:288)
	at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:108)
	at org.apache.spark.SparkContext.clean(SparkContext.scala:2104)
	at org.apache.spark.rdd.RDD$$anonfun$map$1.apply(RDD.scala:370)
	at org.apache.spark.rdd.RDD$$anonfun$map$1.apply(RDD.scala:369)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
	at org.apache.spark.rdd.RDD.map(RDD.scala:369)
	at org.apache.spark.api.java.JavaRDDLike$class.map(JavaRDDLike.scala:93)
	at org.apache.spark.api.java.AbstractJavaRDDLike.map(JavaRDDLike.scala:45)
	at nlb.predict.deeplearning.MyRegExpExample.loadAndTransform(MyRegExpExample.java:123)
	at nlb.predict.deeplearning.MyRegExpExample.main(MyRegExpExample.java:47)
Caused by: java.io.NotSerializableException: sun.nio.cs.UTF_8
Serialization stack:
	- object not serializable (class: sun.nio.cs.UTF_8, value: UTF-8)
	- field (class: org.datavec.api.records.reader.impl.regex.RegexSequenceRecordReader, name: charset, type: class java.nio.charset.Charset)
	- object (class org.datavec.api.records.reader.impl.regex.RegexSequenceRecordReader, org.datavec.api.records.reader.impl.regex.RegexSequenceRecordReader@7a7cc52c)
	- field (class: org.datavec.spark.transform.misc.StringToWritablesFunction, name: recordReader, type: interface org.datavec.api.records.reader.RecordReader)
	- object (class org.datavec.spark.transform.misc.StringToWritablesFunction, org.datavec.spark.transform.misc.StringToWritablesFunction@161f6623)
	- field (class: org.apache.spark.api.java.JavaPairRDD$$anonfun$toScalaFunction$1, name: fun$1, type: interface org.apache.spark.api.java.function.Function)
	- object (class org.apache.spark.api.java.JavaPairRDD$$anonfun$toScalaFunction$1, <function1>)
	at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:40)
	at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:46)
	at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:100)
	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:295)
	... 13 more

This code is based on:

* deeplearning4j-core: 0.9.1
* datavec-spark_2.11: 0.9.1_spark_2
* spark-core_2.11: 2.1.2

I run it on Windows 7 Entreprise.

Do you know if this is a bug and if there is a workaround?

**Comment by nlebreton** [comment]
The same exception is thrown while calling the following line:

RegexSequenceRecordReader recordReader = new RegexSequenceRecordReader(REG_EXP, 0);	

This is because of the following line in RegexSequenceRecordReader:

public static final Charset DEFAULT_CHARSET = Charset.forName("UTF-8");

It works while calling the following code:

RegexLineRecordReader recordReader = new RegexLineRecordReader(REG_EXP, 0);	

Unfortunately, I need the data to be loaded as a sequence and I need the errors to be skipped.

**Comment by saudet** [comment]
Do you think using the file.encoding system property as default would be a
better idea maybe?

**Comment by nlebreton** [comment]
Hi Samuel,

Setting the default encoding will change nothing. Indeed, the root cause of this issue is the fact that the type of DEFAULT_CHARSET and charset is Charset and that Charset subtype is not serializable. 

I have noticed that only the method name() is called on the field charset. I have tried to replace the field charset by the field charsetName of type String and the call of charset.name() by the field charsetName. The type String being serializable, it worked. 

Unfortunately, there is an issue later:

Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost, executor driver): java.util.NoSuchElementException
	at java.util.Collections$EmptyIterator.next(Collections.java:4189)
	at org.datavec.api.records.reader.impl.FileRecordReader.advanceToNextLocation(FileRecordReader.java:199)
	at org.datavec.api.records.reader.impl.FileRecordReader.nextRecord(FileRecordReader.java:177)
	at org.datavec.api.records.reader.impl.FileRecordReader.next(FileRecordReader.java:89)
	at org.datavec.spark.transform.misc.StringToWritablesFunction.call(StringToWritablesFunction.java:41)
	at org.datavec.spark.transform.misc.StringToWritablesFunction.call(StringToWritablesFunction.java:33)
	at org.apache.spark.api.java.JavaPairRDD$$anonfun$toScalaFunction$1.apply(JavaPairRDD.scala:1040)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:393)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at scala.collection.AbstractIterator.to(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1336)
	at org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$29.apply(RDD.scala:1354)
	at org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$29.apply(RDD.scala:1354)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1954)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1954)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:325)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1435)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1423)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1422)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1422)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:802)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1650)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1605)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1594)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:628)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1928)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1941)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1954)
	at org.apache.spark.rdd.RDD$$anonfun$take$1.apply(RDD.scala:1354)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
	at org.apache.spark.rdd.RDD.take(RDD.scala:1327)
	at org.apache.spark.rdd.RDD$$anonfun$first$1.apply(RDD.scala:1368)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
	at org.apache.spark.rdd.RDD.first(RDD.scala:1367)
	at org.apache.spark.api.java.JavaRDDLike$class.first(JavaRDDLike.scala:538)
	at org.apache.spark.api.java.AbstractJavaRDDLike.first(JavaRDDLike.scala:45)
	at org.datavec.spark.transform.SparkTransformExecutor.execute(SparkTransformExecutor.java:169)
	at org.datavec.spark.transform.SparkTransformExecutor.execute(SparkTransformExecutor.java:94)
	at nlb.predict.deeplearning.MyRegExpExample.loadAndTransform(MyRegExpExample.java:136)
	at nlb.predict.deeplearning.MyRegExpExample.main(MyRegExpExample.java:48)
Caused by: java.util.NoSuchElementException
	at java.util.Collections$EmptyIterator.next(Collections.java:4189)
	at org.datavec.api.records.reader.impl.FileRecordReader.advanceToNextLocation(FileRecordReader.java:199)
	at org.datavec.api.records.reader.impl.FileRecordReader.nextRecord(FileRecordReader.java:177)
	at org.datavec.api.records.reader.impl.FileRecordReader.next(FileRecordReader.java:89)
	at org.datavec.spark.transform.misc.StringToWritablesFunction.call(StringToWritablesFunction.java:41)
	at org.datavec.spark.transform.misc.StringToWritablesFunction.call(StringToWritablesFunction.java:33)
	at org.apache.spark.api.java.JavaPairRDD$$anonfun$toScalaFunction$1.apply(JavaPairRDD.scala:1040)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:393)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at scala.collection.AbstractIterator.to(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1336)
	at org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$29.apply(RDD.scala:1354)
	at org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$29.apply(RDD.scala:1354)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1954)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1954)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:325)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Do you think this exception is related to the change I have made or that this is another issue ?

**Comment by AlexDBlack** [comment]
Fixed here, will be merged soon: https://github.com/deeplearning4j/DataVec/pull/463

As for the NoSuchElementException: that's likely not related to this serialization issue.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/DataVec/pull/463
