### ISSUE TITLE
nextRecord() has not been implemented for SVMLightRecordReader

### ISSUE THREAD

**Issue by liufuyang** [deeplearning4j/DataVec#484]
#### Issue Description

Please describe your issue, along with:
- expected behavior
SVMLightRecordReader should just work as other RecordReader

- encountered behavior
```
Exception in thread "main" java.lang.UnsupportedOperationException: nextRecord has not been implemented for SVMLightRecordReader
	at org.datavec.api.records.reader.impl.misc.SVMLightRecordReader.nextRecord(SVMLightRecordReader.java:274)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:300)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:393)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:51)
	at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator$AsyncPrefetchThread.run(AsyncDataSetIterator.java:417)
```

Perhaps we need to uncomment here and implement this method?
https://github.com/deeplearning4j/DataVec/blob/master/datavec-api/src/main/java/org/datavec/api/records/reader/impl/misc/SVMLightRecordReader.java#L280

(Or maybe add some unit test for this method as well?)

**Comment by saudet** [comment]
Yes, it needs to be implemented. Could you send a pull request? It would be appreciated!

**Comment by liufuyang** [comment]
Yep, I can try do that later on :)

**Comment by liufuyang** [comment]
@saudet PR submitted :)
