### ISSUE TITLE
CSVRecordReader cannot parse tab delimited file

### ISSUE THREAD

**Issue by tastyminerals** [deeplearning4j/DataVec#492]
#### Issue Description
I am trying to read the following .csv file delimited by tabs:
```csv
5476	<para>	<para>	56.69	8.0	199	127.68	0	1	0	0	0	0	0	0	0	0	0	0	0	0	0
5476	<unk>	word2	56.69	8.0	32	127.68	1	1	0	0	0	0	0	0	0	1	0	0	0	0	1
5476	word1	word2	91.37	8.0	23	127.68	1	1	1	0	0	0	0	0	1	0	0	0	0	0	1
5476	<punct>	-	116.71	8.0	2	127.68	0	1	0	0	0	0	0	0	0	0	0	1	0	0	0
5476	<unk>	word2	121.6	8.0	54	127.68	1	1	0	0	1	0	0	0	0	1	0	0	0	0	0
5476	<punct>	.	176.27	8.0	2	127.68	0	1	0	0	0	0	0	0	0	0	0	1	0	0	0
5476	<dig>	5-7	180.72	8.0	11	127.68	0	1	0	0	0	0	0	0	0	0	0	0	1	0	0
5476	<punct>	-	194.5	8.0	2	127.68	0	1	0	0	0	0	0	0	0	0	0	1	0	0	0
5476	<dig>	60312	19.39	8.0	22	17.68	0	1	0	0	0	0	0	0	0	0	0	0	1	0	0
5476	word1	word2	23.85	8.0	32	12.6	1	1	0	0	0	0	0	0	0	0	0	0	0	0	0
```
I am using the following chunk of code:
```scala
def readDatasetCSV() = {
  val reader: RecordReader = new CSVRecordReader('\t')
  reader.initialize(new FileSplit(new File("test.csv")))
  var diter: DataSetIterator = new RecordReaderDataSetIterator(reader, 1, 21, 2)
  while (diter.hasNext()) {
    val ds = diter.next()
    println(ds)
  }
}

```

and getting the following error:
```java
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.countLength(RecordReaderMultiDataSetIterator.java:334)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertWritables(RecordReaderMultiDataSetIterator.java:376)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertFeaturesOrLabels(RecordReaderMultiDataSetIterator.java:271)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.nextMultiDataSet(RecordReaderMultiDataSetIterator.java:234)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.next(RecordReaderMultiDataSetIterator.java:177)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:306)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:393)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:51)
	at net.gini.pia.romain.model.DatasetLoader$.readDatasetCSV(torchModel.scala:30)
	at net.gini.pia.romain.model.test$.delayedEndpoint$net$gini$pia$romain$model$test$1(test.scala:7)
	at net.gini.pia.romain.model.test$delayedInit$body.apply(test.scala:3)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
```

#### Version Information

* Deeplearning4j: 0.9.1
* platform: Linux

**Comment by AlexDBlack** [comment]
So it turns out this is not a bug in the library at all: rather, you are using the CSVRecordReader(int skipNumLines) constructor. The char is being cast to an integer there.
So a bug? No. Easy mistake to make? Yes.
I've added a 'delimiter character only' constructor here: https://github.com/deeplearning4j/DataVec/pull/493
