### ISSUE TITLE
Fix classpath resolving of test dependencies for image tests.

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/DataVec#91]
Resource 'testImages/class0/0.jpg' cannot be found.
Stacktrace

java.lang.IllegalStateException: Resource 'testImages/class0/0.jpg' cannot be found.
    at org.datavec.api.util.ClassPathResource.getUrl(ClassPathResource.java:83)
    at org.datavec.api.util.ClassPathResource.getFile(ClassPathResource.java:110)
    at org.datavec.api.util.ClassPathResource.getFile(ClassPathResource.java:97)
    at org.datavec.image.recordreader.TestImageRecordReader.testMetaData(TestImageRecordReader.java:43)

**Comment by huitseeker** [comment]
We haven't been able to reproduce this for a while. Should it be closed ?

**Comment by huitseeker** [comment]
Not reproducible any more https://gist.github.com/463d751333ceace91d20d3d578abdd6f
